### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by whatSocks** [iver56/emoji-art-generator#7]
Trying to run and having trouble with dependencies - is there any chance you can add a requirements file so I can troubleshoot?

**Comment by iver56** [comment]
Dependencies are specified in [environment.yml](https://github.com/iver56/emoji-art-generator/blob/master/environment.yml). If you have Anaconda or Miniconda installed, you can conveniently install all required dependencies into a separate Python environment, as shown in [README](https://github.com/iver56/emoji-art-generator#setup). I will not add a requirements.txt file, but you can create your own if you require it
